# Generated by Django 6.1 on 2026-09-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferred_currency', to='common.currency'),
        ),
    ]
